# Generated by Django 4.2.2 on 2023-06-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LineApp', '0003_comentario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineup',
            name='bando',
            field=models.IntegerField(choices=[(-1, 'Seleccionar'), (1, 'Instrumentos'), (2, 'Accesorios')], default=-1, verbose_name='Tipo instrumento'),
        ),
        migrations.AlterField(
            model_name='lineup',
            name='incorporacion',
            field=models.CharField(max_length=200, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='lineup',
            name='mapa',
            field=models.CharField(max_length=30, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='lineup',
            name='titulo',
            field=models.CharField(max_length=50, verbose_name='Nombre Producto'),
        ),
    ]
